CREATE TABLE banks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) UNIQUE
);

CREATE TABLE reviews (
    id VARCHAR2(20) PRIMARY KEY,
    bank_id NUMBER REFERENCES banks(id),
    review_text CLOB,
    rating NUMBER,
    review_date DATE,
    source VARCHAR2(50),
    sentiment_label VARCHAR2(20),
    sentiment_score FLOAT,
    theme VARCHAR2(100),
    keywords VARCHAR2(500)
);
